import { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    appName: "AquaVera",
    appTagline: "Irrigation Water Management Platform",
    langLabel: "EN",
    langNext: "Switch to Marathi",

    loginTitle: "Welcome to AquaVera",
    loginSubtitle: "Enter your mobile number to continue",
    mobileLabel: "Mobile Number",
    mobilePlaceholder: "Enter 10-digit mobile number",
    sendOtp: "Send OTP",
    otpTitle: "Verify OTP",
    otpSubtitle: "Enter the 4-digit code sent to",
    otpLabel: "One-Time Password",
    verifyOtp: "Verify & Continue",
    resendOtp: "Resend OTP",
    changeMobile: "Change Number",
    invalidMobile: "Enter a valid 10-digit mobile number",
    invalidOtp: "Enter a valid 4-digit OTP",

    profileSetupTitle: "Complete Your Profile",
    profileSetupSubtitle: "Required for billing and verification",
    fullNameLabel: "Full Name",
    fullNamePlaceholder: "Enter your full name",
    aadhaarLabel: "Aadhaar Last 4 Digits",
    aadhaarPlaceholder: "Enter last 4 digits",
    landIdLabel: "Land ID (7/12 Number)",
    landIdPlaceholder: "e.g. MH-PU-7/12-00123",
    landAreaLabel: "Land Area (Hectares)",
    landAreaPlaceholder: "e.g. 2.5",
    beneficiaryTypeLabel: "Beneficiary Type",
    waterSourceLabel: "Water Source",
    registeredWUA: "Registered Water User Association",
    individualBeneficiary: "Individual Beneficiary",
    assuredMajorReservoir: "Assured Supply - Major Reservoir",
    assuredMediumCanal: "Assured Supply - Medium Canal / Storage Tank",
    regulatedWithLoss: "Regulated Supply with Transmission Losses",
    partlyRegulated: "Partly Regulated Supply",
    userMaintainedReservoir: "User-Maintained Reservoir / Bhandara",
    saveProfile: "Save and Continue",
    profileRequired: "All fields are required",
    invalidAadhaar: "Enter valid last 4 digits",

    dashboardTitle: "Dashboard",
    greeting: "Good morning",
    landSummary: "Land Details",
    landId: "Land ID",
    landArea: "Land Area",
    lastCrop: "Last Crop",
    noCropOnRecord: "No crop on record",
    requestWater: "Request Irrigation Water",
    requestWaterSubtitle: "Submit a new water request",
    myRequests: "My Requests",
    noRequests: "No requests yet",
    noRequestsSubtitle: "Submit your first water request to begin",
    billingSummary: "Billing Summary",
    totalBill: "Total Bill",
    totalPaid: "Amount Paid",
    totalUnpaid: "Amount Pending",
    viewAll: "View All",

    requestFormTitle: "New Water Request",
    cropTypeLabel: "Crop Type",
    cropTypePlaceholder: "Select crop type",
    seasonLabel: "Season",
    durationLabel: "Duration (Days)",
    durationPlaceholder: "Number of irrigation days",
    durationHelper: "Enter total number of irrigation days required",
    selectedLand: "Selected Land",
    uploadPhotoLabel: "Crop Field Photo",
    uploadPhotoHelper: "Capture or upload a photo for AI verification",
    openCamera: "Open Camera",
    uploadFromGallery: "Upload from Gallery",
    changePhoto: "Change Photo",
    geoTagLabel: "Location",
    geoTagValue: "Pune, Maharashtra",
    geoTagNote: "Auto-detected from device",
    billPreviewTitle: "Estimated Bill",
    billPreviewNote: "Final amount may vary after officer verification",
    rateApplied: "Rate Applied",
    perHectare: "per hectare",
    submitRequest: "Submit Request",
    cropRequired: "Please select a crop type",
    seasonRequired: "Please select a season",
    durationRequired: "Please enter number of days",

    foodGrains: "Food Grains and Other Crops",
    sugarcane: "Sugarcane",
    banana: "Banana",
    cotton: "Cotton",
    horticulture: "Horticulture",

    kharif: "Kharif",
    rabi: "Rabi",
    hotWeather: "Hot Weather",

    aiVerifyingTitle: "Verifying Your Request",
    aiVerifyingSubtitle: "AI is analyzing your crop field photo. Please wait.",

    approvedTitle: "Request Approved",
    approvedMessage: "Your irrigation water request has been verified and approved.",
    reviewTitle: "Under Review",
    reviewMessage: "Your request requires manual verification. An officer will review it within 2 working days.",
    estimatedBill: "Estimated Bill",
    goToDashboard: "Go to Dashboard",

    statusApproved: "Approved",
    statusPending: "Pending",
    statusNeedsReview: "Under Review",

    navDashboard: "Dashboard",
    navRequests: "Requests",
    navBilling: "Billing",

    billingTitle: "Billing",
    requestId: "Request ID",
    crop: "Crop",
    season: "Season",
    duration: "Duration",
    days: "days",
    amount: "Amount",
    paymentStatus: "Payment",
    paid: "Paid",
    unpaid: "Pending",
    noBillingRecords: "No billing records found",
    hectares: "ha",
    beneficiaryType: "Beneficiary Type",
    waterSource: "Water Source",

    requestsTitle: "All Requests",
    submittedOn: "Submitted",
    billAmount: "Bill Amount",
    fieldRequired: "This field is required"
  },

  mr: {
    appName: "एक्वाव्हेरा",
    appTagline: "सिंचन जल व्यवस्थापन प्रणाली",
    langLabel: "मराठी",
    langNext: "हिंदीवर स्विच करा",

    loginTitle: "एक्वाव्हेरामध्ये आपले स्वागत आहे",
    loginSubtitle: "पुढे जाण्यासाठी आपला मोबाइल नंबर टाका",
    mobileLabel: "मोबाइल नंबर",
    mobilePlaceholder: "१०-अंकी मोबाइल नंबर टाका",
    sendOtp: "OTP पाठवा",
    otpTitle: "OTP तपासा",
    otpSubtitle: "यावर पाठवलेला ४-अंकी कोड टाका",
    otpLabel: "वन-टाइम पासवर्ड",
    verifyOtp: "तपासा आणि पुढे जा",
    resendOtp: "OTP पुन्हा पाठवा",
    changeMobile: "नंबर बदला",
    invalidMobile: "वैध १०-अंकी मोबाइल नंबर टाका",
    invalidOtp: "वैध ४-अंकी OTP टाका",

    profileSetupTitle: "आपली प्रोफाइल पूर्ण करा",
    profileSetupSubtitle: "बिलिंग आणि तपासणीसाठी आवश्यक",
    fullNameLabel: "पूर्ण नाव",
    fullNamePlaceholder: "आपले पूर्ण नाव टाका",
    aadhaarLabel: "आधार शेवटचे ४ अंक",
    aadhaarPlaceholder: "शेवटचे ४ अंक टाका",
    landIdLabel: "जमीन ID (७/१२ क्रमांक)",
    landIdPlaceholder: "उदा. MH-PU-7/12-00123",
    landAreaLabel: "जमीन क्षेत्र (हेक्टर)",
    landAreaPlaceholder: "उदा. २.५",
    beneficiaryTypeLabel: "लाभार्थी प्रकार",
    waterSourceLabel: "पाण्याचा स्रोत",
    registeredWUA: "नोंदणीकृत जलवापर संस्था",
    individualBeneficiary: "वैयक्तिक लाभार्थी",
    assuredMajorReservoir: "निश्चित पुरवठा - मोठे धरण",
    assuredMediumCanal: "निश्चित पुरवठा - मध्यम कालवा / साठवण तलाव",
    regulatedWithLoss: "नियमित पुरवठा - संप्रेषण तोट्यांसह",
    partlyRegulated: "अंशतः नियमित पुरवठा",
    userMaintainedReservoir: "वापरकर्त्याने देखभाल केलेले धरण / बंधारा",
    saveProfile: "जतन करा आणि पुढे जा",
    profileRequired: "सर्व माहिती आवश्यक आहे",
    invalidAadhaar: "वैध शेवटचे ४ अंक टाका",

    dashboardTitle: "डॅशबोर्ड",
    greeting: "सुप्रभात",
    landSummary: "जमीन तपशील",
    landId: "जमीन ID",
    landArea: "जमीन क्षेत्र",
    lastCrop: "शेवटचे पीक",
    noCropOnRecord: "पिकाची माहिती नाही",
    requestWater: "सिंचन पाण्याची मागणी करा",
    requestWaterSubtitle: "नवीन पाण्याची मागणी सबमिट करा",
    myRequests: "माझ्या मागण्या",
    noRequests: "अद्याप मागण्या नाहीत",
    noRequestsSubtitle: "सुरुवात करण्यासाठी पहिली मागणी सबमिट करा",
    billingSummary: "बिल सारांश",
    totalBill: "एकूण बिल",
    totalPaid: "भरलेली रक्कम",
    totalUnpaid: "बाकी रक्कम",
    viewAll: "सर्व पहा",

    requestFormTitle: "नवीन पाण्याची मागणी",
    cropTypeLabel: "पिकाचा प्रकार",
    cropTypePlaceholder: "पिकाचा प्रकार निवडा",
    seasonLabel: "हंगाम",
    durationLabel: "कालावधी (दिवस)",
    durationPlaceholder: "सिंचन दिवसांची संख्या",
    durationHelper: "आवश्यक एकूण सिंचन दिवस टाका",
    selectedLand: "निवडलेली जमीन",
    uploadPhotoLabel: "पीक क्षेत्राचा फोटो",
    uploadPhotoHelper: "AI तपासणीसाठी फोटो काढा किंवा अपलोड करा",
    openCamera: "कॅमेरा उघडा",
    uploadFromGallery: "गॅलरीतून अपलोड करा",
    changePhoto: "फोटो बदला",
    geoTagLabel: "स्थान",
    geoTagValue: "पुणे, महाराष्ट्र",
    geoTagNote: "डिव्हाइसवरून आपोआप शोधले",
    billPreviewTitle: "अंदाजे बिल",
    billPreviewNote: "अधिकारी तपासणीनंतर अंतिम रक्कम बदलू शकते",
    rateApplied: "लागू दर",
    perHectare: "प्रति हेक्टर",
    submitRequest: "मागणी सबमिट करा",
    cropRequired: "कृपया पिकाचा प्रकार निवडा",
    seasonRequired: "कृपया हंगाम निवडा",
    durationRequired: "कृपया दिवसांची संख्या टाका",

    foodGrains: "अन्नधान्य आणि इतर पिके",
    sugarcane: "ऊस",
    banana: "केळी",
    cotton: "कापूस",
    horticulture: "फलोत्पादन",

    kharif: "खरीप",
    rabi: "रब्बी",
    hotWeather: "उन्हाळी",

    aiVerifyingTitle: "आपली मागणी तपासली जात आहे",
    aiVerifyingSubtitle: "AI आपल्या पीक क्षेत्राच्या फोटोचे विश्लेषण करत आहे. कृपया थांबा.",

    approvedTitle: "मागणी मंजूर",
    approvedMessage: "आपली सिंचन पाण्याची मागणी AI प्रणालीद्वारे तपासली आणि मंजूर केली गेली आहे.",
    reviewTitle: "पुनरावलोकनाधीन",
    reviewMessage: "आपली मागणी मॅन्युअल तपासणीसाठी पाठवण्यात आली आहे. एक अधिकारी २ कामकाजाच्या दिवसांत तपासेल.",
    estimatedBill: "अंदाजे बिल",
    goToDashboard: "डॅशबोर्डवर जा",

    statusApproved: "मंजूर",
    statusPending: "प्रलंबित",
    statusNeedsReview: "पुनरावलोकनाधीन",

    navDashboard: "डॅशबोर्ड",
    navRequests: "मागण्या",
    navBilling: "बिलिंग",

    billingTitle: "बिलिंग",
    requestId: "मागणी ID",
    crop: "पीक",
    season: "हंगाम",
    duration: "कालावधी",
    days: "दिवस",
    amount: "रक्कम",
    paymentStatus: "देयक",
    paid: "भरलेले",
    unpaid: "बाकी",
    noBillingRecords: "बिलिंग नोंदी आढळल्या नाहीत",
    hectares: "हे",
    beneficiaryType: "लाभार्थी प्रकार",
    waterSource: "पाण्याचा स्रोत",

    requestsTitle: "सर्व मागण्या",
    submittedOn: "सबमिट केलेली तारीख",
    billAmount: "बिलाची रक्कम",
    fieldRequired: "हे क्षेत्र आवश्यक आहे"
  },

  hi: {
    appName: "एक्वावेरा",
    appTagline: "सिंचाई जल प्रबंधन प्रणाली",
    langLabel: "हिंदी",
    langNext: "Switch to English",

    loginTitle: "एक्वावेरा में आपका स्वागत है",
    loginSubtitle: "जारी रखने के लिए अपना मोबाइल नंबर दर्ज करें",
    mobileLabel: "मोबाइल नंबर",
    mobilePlaceholder: "10 अंकों का मोबाइल नंबर दर्ज करें",
    sendOtp: "OTP भेजें",
    otpTitle: "OTP सत्यापित करें",
    otpSubtitle: "इस पर भेजा गया 4 अंकों का कोड दर्ज करें",
    otpLabel: "वन-टाइम पासवर्ड",
    verifyOtp: "सत्यापित करें और जारी रखें",
    resendOtp: "OTP पुनः भेजें",
    changeMobile: "नंबर बदलें",
    invalidMobile: "वैध 10 अंकों का मोबाइल नंबर दर्ज करें",
    invalidOtp: "वैध 4 अंकों का OTP दर्ज करें",

    profileSetupTitle: "अपनी प्रोफ़ाइल पूर्ण करें",
    profileSetupSubtitle: "बिलिंग और सत्यापन के लिए आवश्यक",
    fullNameLabel: "पूरा नाम",
    fullNamePlaceholder: "अपना पूरा नाम दर्ज करें",
    aadhaarLabel: "आधार के अंतिम 4 अंक",
    aadhaarPlaceholder: "अंतिम 4 अंक दर्ज करें",
    landIdLabel: "भूमि ID (7/12 संख्या)",
    landIdPlaceholder: "उदा. MH-PU-7/12-00123",
    landAreaLabel: "भूमि क्षेत्र (हेक्टेयर)",
    landAreaPlaceholder: "उदा. 2.5",
    beneficiaryTypeLabel: "लाभार्थी प्रकार",
    waterSourceLabel: "जल स्रोत",
    registeredWUA: "पंजीकृत जल उपयोगकर्ता संघ",
    individualBeneficiary: "व्यक्तिगत लाभार्थी",
    assuredMajorReservoir: "सुनिश्चित आपूर्ति - प्रमुख जलाशय",
    assuredMediumCanal: "सुनिश्चित आपूर्ति - मध्यम नहर / भंडारण टैंक",
    regulatedWithLoss: "संचरण हानि सहित नियमित आपूर्ति",
    partlyRegulated: "आंशिक रूप से नियमित आपूर्ति",
    userMaintainedReservoir: "उपयोगकर्ता-अनुरक्षित जलाशय / बंधारा",
    saveProfile: "सहेजें और जारी रखें",
    profileRequired: "सभी फ़ील्ड आवश्यक हैं",
    invalidAadhaar: "वैध अंतिम 4 अंक दर्ज करें",

    dashboardTitle: "डैशबोर्ड",
    greeting: "सुप्रभात",
    landSummary: "भूमि विवरण",
    landId: "भूमि ID",
    landArea: "भूमि क्षेत्र",
    lastCrop: "अंतिम फसल",
    noCropOnRecord: "कोई फसल दर्ज नहीं",
    requestWater: "सिंचाई जल का अनुरोध करें",
    requestWaterSubtitle: "नया जल अनुरोध सबमिट करें",
    myRequests: "मेरे अनुरोध",
    noRequests: "अभी तक कोई अनुरोध नहीं",
    noRequestsSubtitle: "शुरू करने के लिए अपना पहला जल अनुरोध सबमिट करें",
    billingSummary: "बिलिंग सारांश",
    totalBill: "कुल बिल",
    totalPaid: "भुगतान की गई राशि",
    totalUnpaid: "बकाया राशि",
    viewAll: "सभी देखें",

    requestFormTitle: "नया जल अनुरोध",
    cropTypeLabel: "फसल का प्रकार",
    cropTypePlaceholder: "फसल का प्रकार चुनें",
    seasonLabel: "मौसम",
    durationLabel: "अवधि (दिन)",
    durationPlaceholder: "सिंचाई दिनों की संख्या",
    durationHelper: "आवश्यक कुल सिंचाई दिन दर्ज करें",
    selectedLand: "चयनित भूमि",
    uploadPhotoLabel: "फसल क्षेत्र फोटो",
    uploadPhotoHelper: "AI सत्यापन के लिए फोटो लें या अपलोड करें",
    openCamera: "कैमरा खोलें",
    uploadFromGallery: "गैलरी से अपलोड करें",
    changePhoto: "फोटो बदलें",
    geoTagLabel: "स्थान",
    geoTagValue: "पुणे, महाराष्ट्र",
    geoTagNote: "डिवाइस से स्वतः पहचाना गया",
    billPreviewTitle: "अनुमानित बिल",
    billPreviewNote: "अधिकारी सत्यापन के बाद अंतिम राशि भिन्न हो सकती है",
    rateApplied: "लागू दर",
    perHectare: "प्रति हेक्टेयर",
    submitRequest: "अनुरोध सबमिट करें",
    cropRequired: "कृपया फसल का प्रकार चुनें",
    seasonRequired: "कृपया मौसम चुनें",
    durationRequired: "कृपया दिनों की संख्या दर्ज करें",

    foodGrains: "खाद्यान्न और अन्य फसलें",
    sugarcane: "गन्ना",
    banana: "केला",
    cotton: "कपास",
    horticulture: "बागवानी",

    kharif: "खरीफ",
    rabi: "रबी",
    hotWeather: "गर्म मौसम",

    aiVerifyingTitle: "आपका अनुरोध सत्यापित हो रहा है",
    aiVerifyingSubtitle: "AI आपके फसल क्षेत्र की फोटो का विश्लेषण कर रहा है। कृपया प्रतीक्षा करें।",

    approvedTitle: "अनुरोध स्वीकृत",
    approvedMessage: "आपका सिंचाई जल अनुरोध AI प्रणाली द्वारा सत्यापित और स्वीकृत किया गया है।",
    reviewTitle: "समीक्षाधीन",
    reviewMessage: "आपका अनुरोध मैन्युअल सत्यापन के लिए भेजा गया है। एक अधिकारी 2 कार्य दिवसों में इसकी समीक्षा करेगा।",
    estimatedBill: "अनुमानित बिल",
    goToDashboard: "डैशबोर्ड पर जाएं",

    statusApproved: "स्वीकृत",
    statusPending: "लंबित",
    statusNeedsReview: "समीक्षाधीन",

    navDashboard: "डैशबोर्ड",
    navRequests: "अनुरोध",
    navBilling: "बिलिंग",

    billingTitle: "बिलिंग",
    requestId: "अनुरोध ID",
    crop: "फसल",
    season: "मौसम",
    duration: "अवधि",
    days: "दिन",
    amount: "राशि",
    paymentStatus: "भुगतान",
    paid: "भुगतान किया",
    unpaid: "बकाया",
    noBillingRecords: "कोई बिलिंग रिकॉर्ड नहीं मिला",
    hectares: "हे",
    beneficiaryType: "लाभार्थी प्रकार",
    waterSource: "जल स्रोत",

    requestsTitle: "सभी अनुरोध",
    submittedOn: "सबमिट किया",
    billAmount: "बिल राशि",
    fieldRequired: "यह फ़ील्ड आवश्यक है"
  }
};

const LangContext = createContext();

export function LangProvider({ children }) {
  const [lang, setLang] = useState('en');
  const cycleLang = () => setLang(prev => prev === 'en' ? 'mr' : prev === 'mr' ? 'hi' : 'en');
  const t = (key) => translations[lang][key] || key;
  return (
    <LangContext.Provider value={{ lang, cycleLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
